version: '3'

services:
  backend:
    build:
      context: ./backend_files
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend_files
    ports:
      - "3000:80"
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
